export const FETCH_ALL = 'FETCH_ALL';
export const CREATE_RUBRIC = 'CREATE_RUBRIC';
export const UPDATE_RUBRIC = 'UPDATE_RUBRIC';
export const DELETE_RUBRIC = 'DELETE_RUBRIC';

export const FETCH_ALL_FILES = 'FETCH_ALL_FILES';

export const FETCH_ALL_FILEDATA = 'FETCH_ALL_FILEDATA';
export const CREATE_FILEDATA = 'CREATE_FILEDATA';
export const UPDATE_FILEDATA = 'UPDATE_FILEDATA';
export const DELETE_FILEDATA = 'DELETE_FILEDATA';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

